### ISSUE TITLE
Not able to Edit Course[Admin Panel]

### ISSUE THREAD

**Issue by mdccxxix** [CodeShala/codeshala.org#13]
Not able to edit course from admin panel. Actions are not defined I guess.

**Comment by vipinkhushu** [comment]
Yes, Course details can't be edited or deleted as of now, as functionality has not been defined yet. Edit and delete functionality was defined just for editing Batches for Issue https://github.com/CodeShala/codeshala.org/issues/9

**Comment by vipinkhushu** [comment]
This is a TODO feature and has been added in the list of implementation at https://github.com/CodeShala/codeshala.org/issues/15
