### ISSUE TITLE
Auto Slides for feedback - Home Page

### ISSUE THREAD

**Issue by mdccxxix** [CodeShala/codeshala.org#39]
We need to add 15+ feedback on the home page and I guess, 3 feedback/review at a time will look good. Three feedback will not take much space on home page and we can use auto slides(5+ slides) for other feedback. Each slide will have atleast 3 feedback. 

The same thing will be reflected on codeshala for kids.

**Comment by vipinkhushu** [comment]
@mdccxxix Please add as many feedbacks as you want from the admin panel
