### ISSUE TITLE
Add seperate course page

### ISSUE THREAD

**Issue by vipinkhushu** [CodeShala/codeshala.org#4]
We need to have a dedicated page that shows all of our courses which provides basic detail of the course.
All the courses need to have a dedicated page which provides deep details of the course.

**Comment by mdccxxix** [comment]
- Courses page should have all courses listed. 
- User should be able to register for the course.
- The registration form should support registrations for multiple locations(centers).
- Individual course page should have all information about course curriculum, duration, start date, fee, mentors and teaching assistants. 
- Individual course page should have feedback from earlier batches.  
- User should be able to access course material from the course catalog.  
- Admin should be able to add notes/discussion for a course.

**Comment by vipinkhushu** [comment]
- [ ]  Show batches detail on course page

**Comment by vipinkhushu** [comment]
Last 2 points added to TODO list, here -> https://github.com/CodeShala/codeshala.org/issues/15
