### ISSUE TITLE
CS Blog

### ISSUE THREAD

**Issue by mdccxxix** [CodeShala/codeshala.org#5]
Add feature so that user can write and publish a post on the platform. 
- Author should be able to write blog using the platform. 
- Author should be able to upload images. 
- Blog should support latex syntaxes.  
- User should be able to search a blog post by its title, tags or author.  
- Author should be able to add tags to the blog.  
- Blog post should be reflected in Author's profile.   
- There should be two section, Trending and New blog posts. 
- User should be able to filter blog post by number of votes and tags.  
- Blog post should support comments.
- Blog post should have upvote/downvote options.

**Comment by vipinkhushu** [comment]
This issue was moved to CodeShala/blog.codeshala.org#1
